stages:
  - setup
  - run

setup_environment:
  stage: setup
  image: python:3.9
  script:
    - echo "SHARP done join @SHARPCRACKS"

run_script:
  stage: run
  image: python:3.9
  dependencies:
    - setup_environment
  script:
    - pip install telebot flask aiogram python-telegram-bot pymongo  && chmod +x * && python3 s.py

restart_pipeline:
  stage: run
  image: python:3.9
  script:
    - echo "Sleeping for 1 hour before restarting..."
    - sleep 3600
    - echo "Restarting the pipeline..."
    - curl -X POST -F token=$CI_JOB_TOKEN -F ref=$CI_COMMIT_REF_NAME https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline
  only:
    - main  # Adjust if using a different branch
